### ISSUE TITLE
Add support for wide widget form controls

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-widget-customizer#18]
Widget form controls are able to specify their widget, like if a widget's form needs extra space to be able to fit the fields inside of it. We should allow customize widget form controls in the customizer panel to expand outside of the sidebar area when they are expanded.

But how can a wide widget control expand over the preview?

![customize__wordpress_develop___just_another_wordpress_site_and_widgets__wordpress_develop__wordpress-3](https://f.cloud.github.com/assets/134745/1382917/f4b5c086-3b34-11e3-8204-f86edc8380fe.png)

**Comment by westonruter** [comment]
via @helenhousandi‎: http://plugins.svn.wordpress.org/css/trunk/motif.js

**Comment by westonruter** [comment]
Actually, the consensus may be to eliminate support for wide widget controls altogether.

**Comment by shaunandrews** [comment]
> We should allow customize widget form controls in the customizer panel to expand outside of the sidebar area when they are expanded.

No, we shouldn't.

**Comment by westonruter** [comment]
@shaunandrews :smile: OK! :+1:

**Comment by westonruter** [comment]
@shaunandrews here's another instance of wide widgets: the Jetpack Widget Visibility module.

> ![customize_twenty_thirteen__wordpress](https://f.cloud.github.com/assets/134745/1417912/9acc85d4-3fa1-11e3-8a7e-11d078d333c9.png)

See the relevant code in [`widget-conditions.js`](http://plugins.trac.wordpress.org/browser/jetpack/trunk/modules/widget-visibility/widget-conditions/widget-conditions.js?rev=755289#L15) which tries to force a widget form control to be wide:

``` js
// The expanded widget must be at least 400px wide in order to
// contain the visibility settings. IE wasn't handling the
// margin-left value properly.

if ( $widget.attr( 'style' ) )
    $widget.data( 'original-style', $widget.attr( 'style' ) );

var currentWidth = $widget.width();

if ( currentWidth < 400 ) {
    var extra = 400 - currentWidth;
    $widget.css( 'position', 'relative' ).css( 'left', '-' + extra + 'px' ).css( 'width', '400px' );
}
```

I've added a commit (5d6dd72901322b011284d50c9b9dd68a85c15af9) to try to prevent plugins from forcing widgets to be wide in the customizer and break the layout, but doing so could break the layout of the control's contents.

/cc @cfinke

**Comment by westonruter** [comment]
As noted in #39, here's how the Widget Visibility controls now look when rendered in the customizer:

> ![customize_twenty_thirteen__wordpress](https://f.cloud.github.com/assets/134745/1418054/a95c705e-3fa7-11e3-8189-873e35265136.png)

**Comment by westonruter** [comment]
@shaunandrews here's an extreme example of wide widget form controls: http://wordpress.org/plugins/black-studio-tinymce-widget/screenshots/

> ![image](https://f.cloud.github.com/assets/134745/1495293/70776ddc-47e7-11e3-86ce-f7021eae8a9d.png)

**Comment by westonruter** [comment]
Another extreme example: http://wordpress.org/plugins/mini-loops/screenshots/

> ![image](https://f.cloud.github.com/assets/134745/1495458/9223ac22-47ea-11e3-946a-856a9e509a84.png)

**Comment by westonruter** [comment]
http://core.trac.wordpress.org/ticket/26117

**Comment by PeterKnight** [comment]
Right now it's pretty difficult to expand the width and have it expand outside the side panel, at least not without a bunch of js trickery. I've tried floating a widget outside the side panel altogether but that comes with a usability cost. 

Any thoughts on displaying the widget controls floated next to the actual widget in the page?

**Comment by shaunandrews** [comment]
I've been thinking about this, and I'd like to avoid covering the preview if it all possible.

## 

Shaun

**Comment by westonruter** [comment]
What about if we open the wide-widget control in another monitor!? If they lack another monitor, the control can pop-up on their smartphone or tablet :wink: 

All joking aside, this is a tough issue.

@shaunandrews @PeterKnight Here's an idea that just came to me: just as the new widget addition panel shifts in from the left, what if wide widget controls were placed inside of a panel that shifts in from the top (or from the bottom?

**Comment by PeterKnight** [comment]
It's definitely a tough one.

I think there would be problems with having another panel slide in from the top or bottom, the widget itself might get obscured or the viewing area would be too small. Then there's the issue that some widgets controls take up a lot of height, and some take up more width. 

One advantage of having a floating widget panel that hugs the edge of the widget: the JS can figure out what the best way to display the widget settings panel and keep the widget that is being changed in view. After all, when in widget edit mode, all that matters for the task at hand is seeing the widget and changing it's settings. The main panel on the left could even be collapsed while in widget edit mode.

**Comment by shaunandrews** [comment]
A floating panel is likely the best solution. My biggest concern with this is that it add a whole different level of UI for managing content in the customizer. I'm not against it (in fact, some of my sketches show this exact solution), but I worry about how it would be perceived with the core developers — also it seems like a lot of work.

**Comment by shaunandrews** [comment]
For reference, check out #17

**Comment by PeterKnight** [comment]
I think the screen you have at #17 looks great. Wouldn't positive user tests make it hard for core devs to deny the approach? IMO it's the most elegant solution, I do get the work portion of it though because of the extra moving parts. I don't think there's a downside though, even if it doesn't land in core, it will become the best way to modify widgets.

Scribu's front end editor has a widget editor (you've probably used it), his version loads the widgets panel in place but obscures the view of the widget (temporarily exchanging the widget contents with the editing panel). It's intuitive but limited and also suffers from css conflicts because unlike the customizer, it doesn't benefit from the iframe isolating the stylesheets. But it does demonstrate the value of having the options panel right there on the live page.

What I do like about this and other developments across the core code base is the ability to invoke individual UI components anywhere. We can now get the wp_editor anywhere, the media dialog anywhere and so forth, image editing is going in that direction too I think. I think the only way to figure out if this approach will work as well with widgets is to attempt it.

**Comment by westonruter** [comment]
Closely related to [#26701 Text and RSS Widgets Unusable on Mobile](https://core.trac.wordpress.org/ticket/26701), a fix in WordPress 3.8.1

**Comment by westonruter** [comment]
Here's a few more mocks from @MichaelArestad: https://cloudup.com/iqH4tGUbQPn

**Comment by westonruter** [comment]
Today on #wordpress-dev, I mentioned to @nacin in response to his request for a status update:

> we're still stuck on a good path forward for handling wide widget controls

He replied:

> let's assume we just made wide widget controls wide, no matter how ugly it is
> we can't make it extend out over the panel?
> honestly, what to do with wide widgets seems like very low priority.

I said:

> it seems I can only get the control to break out of the customizer panel with a position:fixed
> I tried position:relative with a z-index:infinity, but it doesn't work
> ok, I think position: fixed will work nicely actually for a quick solution. I'll follow that up separately.

So I think the quickest solution will be to apply a `position:fixed` on the contents of the widget control. This will allow the widget to appear over the panel and it can be dragged around with some.

See [full transcript](https://irclogs.wordpress.org/chanlog.php?channel=wordpress-dev&day=2014-02-04&sort=asc#m783581).

**Comment by PeterKnight** [comment]
Why not use jquery UI position to float the controls next to the widget in the preview and use it for both narrow and wide widgets so it is a consistent experience? 

I don't see how the alternatives would work much better. Seems like Nacin was for making the panel wider, but that brings up the issue of triggering responsive layouts. Using position fixed the controls might clip or hover over the preview area which might obscure the widget you're editing. When I tried this a few months ago with twenty fourteen that's the issue I had because of the left sidebar.
