### ISSUE TITLE
JS error - setting.transport is undefined

### ISSUE THREAD

**Issue by ccardinaux** [xwp/wp-widget-customizer#91]
I tried out the plugin once and it worked well - on the same site, when I came back to it on a different day I got a JavaScript error in widget-customizer-preview.js (see image).

Browser is Chrome 32 on Windows 7. Running WordPress 3.8.1 multisite on a local install, and the plugin is working fine on another site on the same install.
![widget-customizer-js-error](https://f.cloud.github.com/assets/1361275/2130093/4290d78a-928f-11e3-9693-b49f61ed51d8.PNG)

**Comment by westonruter** [comment]
Thanks for reporting this! It actually is an issue I encountered and fixed 3 days ago in commit 42adb151de2d812a099d2358cc4223931a2fa8cc. The problem happens when there is a widget is left in a sidebar when the registered widget went away, for example due to a plugin deactivation. if possible, can you checkout the `develop` branch and see if that indeed solves the problem?

**Comment by ccardinaux** [comment]
That fixed it - thanks!

**Comment by westonruter** [comment]
@ccardinaux thanks for the great bug report!
